# File name: rail.kv
#:kivy 1.10.0
<MyButton@Button>:
    size_hint: 0.25, .10
    color: (1.0, 1.0, 1.0, 1.0)
    font_size: 30
    background_color: (1,1.5,0,1)  
    size_hint: 0.25, .10

<MyToggleButton@ToggleButton>:
    size_hint: 0.25, .10
    color: (1.0, 1.0, 1.0, 1.0)
    font_size: 30
    background_color: (1.0, 0.0, 1.0, 1.0)


Controller:
<Controller>:
    log_results: log_list
    FloatLayout:
        Label:
            text: "Welcome Home"
            pos_hint: {'x': 0, 'y': 0.85}
            font_size: 30
            size_hint: 1, .1
            color: (1.0, 1.0, 1.0, 1.0)
            background_color: (0.0, 1.0, 0.0, 1.0)

        MyButton:
            text: "Train New"
            pos_hint: {'x': 0, 'y': 0.35}
            

        MyButton:
            text: "Show Errors"
            pos_hint: {'x': 0, 'y': 0.45}
            
        MyToggleButton:
            text: "Run (Test)"
            pos_hint: {'x': 0, 'y': 0.55}
            
        MyToggleButton:
            text: "Collect Data"
            pos_hint: {'x': 0, 'y': 0.65}
            on_state: root.collect_data(*args)            
            
        MyButton:
            text: "TBA"
            pos_hint: {'x': 0.75, 'y': 0.35}
            
        MyButton:
            text: "Graph deflection"
            pos_hint: {'x': 0.75, 'y': 0.45}
            on_press: Roto.show_load()

        MyButton:
            text: "Test Connection"
            pos_hint: {'x': 0.75, 'y': 0.55}
            on_press: root.Check_Connection()
            
        MyButton:
            text: "Test Sensors"
            pos_hint: {'x': 0.75, 'y': 0.65}
            on_press: root.check_sensors()

        ScrollView:
            pos_hint: {'x': 0, 'y': 0.05}
            size_hint: 1, .3
            font_size: 14
            ListView:
                id: log_list                
                 
            
        ToggleButton:
            text: "Map"
            pos_hint: {'x': 0.25, 'y': 0.35}
            size_hint: 0.5, .4
            color: (1.0, 1.0, 1.0, 1.0)
            font_size: 30
            background_color: (1.0, 1.0, 1.0, 1.0)

          
<Roto>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: 1
            size_hint_x: 1
            Button:
                font_size: '30sp'
                text: 'Click here to choose the .csv file that will be used'
                on_release: Roto.show_load()


<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 40
            Button:
                text: "Cancel"
                on_release: Roto.cancel()

            Button:
                text: "Load"
                on_release: Roto.load(filechooser.path, filechooser.selection)
